# Dependencies
markdown:         kramdown
highlighter:      rouge


# Setup
title:            'Quantum resources workshop - Singapore 2023'
tagline:          'Quantum Resources 2023'
description:      'Workshop on quantum resource theories, taking place between 11 - 15 December 2023 in Singapore.'
url:              "https://2023.quantumresources.science"
baseurl:          ''


author:
  name:           'Ryuji Takagi'

paginate:         5

# Custom vars
version:          2.1.0

